# Databricks App Resource Configuration
resources:
  apps:
    unified-job-platform:
      name: unified-job-platform
      description: |
        Enterprise Databricks Job Monitoring & Cost Attribution Platform
        - Real-time job monitoring with Gantt and Matrix views
        - Dynamic cost attribution for serverless workloads
        - ADF pipeline integration for tag correlation
        - AI-powered insights via Genie Spaces
        - Lakebase integration for sub-100ms query performance
      source_code_path: ${workspace.file_path}/app

      resources:
        - name: sql-warehouse
          sql_warehouse:
            id: ${var.warehouse_id}
            permission: CAN_USE
